language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.githubusercontent.com/atykhonov/9213915/raw/1e24383279977f1c20d78007e5d1d51a6f0ac37d/travis.sh | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
script:
  - emacs --version
  - make test

